package tech.bilski.playground.sql;

import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestInstance;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate;

import static org.assertj.core.api.Assertions.assertThat;

@SpringBootTest
@TestInstance(TestInstance.Lifecycle.PER_CLASS)
public class JdbcRepositoryWithArray {

    @Autowired
    private EntityWithArrayJdbcRepository repository;

    @Autowired
    private NamedParameterJdbcTemplate jdbcTemplate;

    @BeforeAll
    void setup() {
        jdbcTemplate.getJdbcOperations()
                    .execute("DROP TABLE IF EXISTS entity_with_array");
        jdbcTemplate.getJdbcOperations()
                    .execute("CREATE TABLE entity_with_array (id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, arr TEXT ARRAY[5])");
    }

    @Test
    void save() {
        var entity = new EntityWithArray();
        entity.arr = new String[]{"first", "second"};
        var saved = repository.save(entity);
        assertThat(saved).isNotNull();
    }

    @Test
    void get() {
        var entity = new EntityWithArray();
        entity.arr = new String[]{"first", "second"};
        var saved = repository.save(entity);

        var read = repository.findById(saved.id);
        assertThat(read).isPresent();
        var readEntity = read.get();
        assertThat(readEntity.arr)
                .hasSize(2)
                .contains("first", "second");
    }

    @Test
    void update() {
        var entity = new EntityWithArray();
        entity.arr = new String[]{"first", "second"};
        var saved = repository.save(entity);
        saved.arr[0] = "third";
        repository.save(saved);

        var read = repository.findById(saved.id);
        assertThat(read).isPresent();
        var readEntity = read.get();
        assertThat(readEntity.arr)
                .hasSize(2)
                .contains("second", "third");
    }
}
