package tech.bilski.playground.sql;

import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestInstance;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate;

@SpringBootTest
@TestInstance(TestInstance.Lifecycle.PER_CLASS)
public class Playground {

    @Autowired
    private NamedParameterJdbcTemplate jdbcTemplate;

    @BeforeAll
    void setup() {
        jdbcTemplate.getJdbcOperations().execute("CREATE TABLE XYZ (id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, list TEXT ARRAY[5])");
    }

    @AfterAll
    void tearDown() {
        jdbcTemplate.getJdbcOperations().execute("DROP TABLE IF EXISTS XYZ");
    }

    @Test
    void x() {
        System.out.println("x");
    }
}
